import Combine
import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case system
    case simplifiedChinese
    case english

    var id: Self { self }

    static func resolve(preference: AppLanguage, preferredLanguages: [String]) -> AppLanguage {
        guard preference == .system else {
            return preference
        }

        return preferredLanguages.first(where: { $0.lowercased().hasPrefix("zh") }) == nil
            ? .english
            : .simplifiedChinese
    }
}

@MainActor
final class AppLanguageSettings: ObservableObject {
    static let shared = AppLanguageSettings()

    var preference: AppLanguage {
        didSet {
            defaults.set(preference.rawValue, forKey: Self.preferenceKey)
            objectWillChange.send()
        }
    }

    private static let preferenceKey = "app.language.preference"
    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        preference = AppLanguage(rawValue: defaults.string(forKey: Self.preferenceKey) ?? "") ?? .system
    }
}

enum AppLocalization {
    static func text(
        _ source: String,
        preference: AppLanguage = currentPreference,
        preferredLanguages: [String] = Locale.preferredLanguages
    ) -> String {
        guard AppLanguage.resolve(preference: preference, preferredLanguages: preferredLanguages) == .english else {
            return source
        }

        return englishTranslations[source] ?? formattedEnglishText(for: source) ?? source
    }

    private static var currentPreference: AppLanguage {
        AppLanguage(rawValue: UserDefaults.standard.string(forKey: "app.language.preference") ?? "") ?? .system
    }

    private static func formattedEnglishText(for source: String) -> String? {
        if source.hasPrefix("来自 ") {
            return "From " + source.dropFirst("来自 ".count)
        }
        if let values = captures(in: source, pattern: #"^快捷键 (.+)$"#) {
            return "Shortcut \(values[0])"
        }
        if let values = captures(in: source, pattern: #"^最近 (\d+) 条，平均 (.+)，最高 (.+)，CPU (.+)，内存 (.+)$"#) {
            return "Latest \(values[0]): avg \(values[1]), max \(values[2]), CPU \(values[3]), memory \(values[4])"
        }
        if let values = captures(in: source, pattern: #"^最近 (\d+) 条，平均 (.+)，最高 (.+)$"#) {
            return "Latest \(values[0]): avg \(values[1]), max \(values[2])"
        }
        if let values = captures(in: source, pattern: #"^最近 (\d+) 条采样事件$"#) {
            return "\(values[0]) recent sampled events"
        }
        if let values = captures(in: source, pattern: #"^共 (\d+) 条，占用 (.+)\n(.+)\n(.+)$"#) {
            return "\(values[0]) items, using \(values[1])\n\(values[2])\n\(values[3])"
        }
        if let values = captures(in: source, pattern: #"^(.+) (.+)/(\d+)条$"#) {
            return "\(values[0]) \(values[1])/\(values[2]) items"
        }
        if let values = captures(in: source, pattern: #"^当前版本 (.+) 已是 GitHub 最新正式 Release。$"#) {
            return "Version \(values[0]) is the latest stable release on GitHub."
        }
        if let values = captures(in: source, pattern: #"^当前版本为 (.+)。GitHub 最新正式 Release 发布于 (.+)。$"#) {
            return "Current version: \(values[0]). The latest stable GitHub release was published on \(values[1])."
        }
        if let values = captures(in: source, pattern: #"^当前版本为 (.+)。GitHub 有新的正式 Release。$"#) {
            return "Current version: \(values[0]). A newer stable release is available on GitHub."
        }
        if let values = captures(in: source, pattern: #"^发现新版本 ClipEase (.+)$"#) {
            return "New ClipEase version \(values[0]) available"
        }
        if let values = captures(in: source, pattern: #"^(.+)，错误 (\d+) 条$"#) {
            return "\(values[0]), \(values[1]) errors"
        }
        if let values = captures(in: source, pattern: #"^缺失图片 (\d+)$"#) {
            return "Missing images: \(values[0])"
        }
        if let values = captures(in: source, pattern: #"^缺失富文本 (\d+)$"#) {
            return "Missing rich-text files: \(values[0])"
        }
        if let values = captures(in: source, pattern: #"^孤立附件 (\d+) 个/(.+)$"#) {
            return "Orphaned attachments: \(values[0]) (\(values[1]))"
        }
        if let values = captures(in: source, pattern: #"^已修复 (\d+) 个孤立附件$"#) {
            return "Repaired \(values[0]) orphaned attachments"
        }
        if let values = captures(in: source, pattern: #"^保存期限已改为：(.+)$"#) {
            return "Retention period changed to: \(values[0])"
        }
        if let values = captures(in: source, pattern: #"^缺失图片：\s*(\d+)\n缺失富文本：\s*(\d+)\n孤立附件：\s*(\d+)\n孤立附件占用：\s*(.+)$"#) {
            return "Missing images: \(values[0])\nMissing rich-text files: \(values[1])\nOrphaned attachments: \(values[2])\nOrphaned attachment storage: \(values[3])"
        }
        if let match = try? NSRegularExpression(pattern: #"^(\d+) 个分组，(\d+) 条内容$"#)
            .firstMatch(in: source, range: NSRange(source.startIndex..., in: source)),
           let groupsRange = Range(match.range(at: 1), in: source),
           let itemsRange = Range(match.range(at: 2), in: source) {
            return "\(source[groupsRange]) groups, \(source[itemsRange]) items"
        }
        let patterns: [(String, (String) -> String)] = [
            (#"^(\d+) 个字符$"#, { "\($0) characters" }),
            (#"^(\d+) 单词$"#, { "\($0) words" }),
            (#"^(\d+) 行$"#, { "\($0) lines" }),
            (#"^(\d+) 个文件$"#, { "\($0) files" }),
            (#"^(\d+) 分钟前$"#, { "\($0) min ago" }),
            (#"^(\d+) 小时前$"#, { "\($0) hr ago" }),
            (#"^(\d+) 天前$"#, { "\($0) days ago" }),
            (#"^(\d+) 天$"#, { "\($0) Days" }),
            (#"^(\d{2}:\d{2}) 恢复$"#, { "Resume at \($0)" }),
            (#"^(\d+) 条$"#, { "\($0) items" })
        ]

        for (pattern, transform) in patterns {
            guard let expression = try? NSRegularExpression(pattern: pattern),
                  let match = expression.firstMatch(
                    in: source,
                    range: NSRange(source.startIndex..., in: source)
                  ),
                  let range = Range(match.range(at: 1), in: source) else {
                continue
            }
            return transform(String(source[range]))
        }
        return nil
    }

    private static func captures(in source: String, pattern: String) -> [String]? {
        guard let expression = try? NSRegularExpression(pattern: pattern),
              let match = expression.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else {
            return nil
        }

        return (1..<match.numberOfRanges).compactMap { index in
            guard let range = Range(match.range(at: index), in: source) else {
                return nil
            }
            return String(source[range])
        }
    }

    private static let englishTranslations: [String: String] = [
        "轻贴设置": "ClipEase Settings",
        "轻贴帮助": "ClipEase Help",
        "关于轻贴": "About ClipEase",
        "好的": "OK",
        "通用": "General",
        "外观": "Appearance",
        "快捷键": "Keyboard Shortcut",
        "记录": "Recording",
        "分组": "Groups",
        "历史数据": "History Data",
        "性能/日志": "Performance & Logs",
        "权限": "Permissions",
        "关于": "About",
        "保存期限和启动方式": "Retention and launch settings",
        "主题、玻璃、卡片和字体": "Theme, glass, cards, and typography",
        "打开或关闭底部历史窗口": "Open or close the history window",
        "记录状态和忽略 App": "Recording state and ignored apps",
        "管理分组、颜色和排序": "Manage groups, colors, and order",
        "导入、导出、备份和本地文件": "Import, export, backup, and local files",
        "采样、图表和日志文件": "Sampling, charts, and log files",
        "自动粘贴需要的系统权限": "System permission required for auto-paste",
        "版本信息和项目入口": "Version information and project links",
        "语言": "Language",
        "界面语言会立即切换；首次安装默认跟随系统语言。": "The interface changes immediately. New installations follow the system language.",
        "跟随系统": "Follow System",
        "简体中文": "Simplified Chinese",
        "英文": "English",
        "浅色": "Light",
        "深色": "Dark",
        "跟随主题": "Follow System",
        "液态玻璃": "Liquid Glass",
        "普通": "Standard",
        "设置": "Settings",
        "编辑": "Edit",
        "暂停 / 恢复记录": "Pause / Resume Recording",
        "预览": "Preview",
        "粘贴": "Paste",
        "粘贴为纯文本": "Paste as Plain Text",
        "复制": "Copy",
        "复制纯文本": "Copy Plain Text",
        "帮助": "Help",
        "退出": "Quit",
        "置顶": "Pinned",
        "简洁好用的 macOS 粘贴板历史助手": "A simple and useful macOS clipboard history manager",
        "版本": "Version",
        "轻贴": "ClipEase",
        "全部剪切板": "All Clipboard",
        "搜索": "Search",
        "复制一段文字后会显示在这里": "Copied items will appear here",
        "正在加载历史": "Loading history",
        "暂无置顶内容": "No pinned items",
        "暂无内容": "No items yet",
        "没有找到匹配的历史": "No matching history found",
        "窗口效果": "Window Effects",
        "立即预览并自动保存": "Preview instantly and save automatically",
        "霜雾": "Frosted",
        "深空": "Deep Space",
        "棱镜": "Prism",
        "全息": "Holographic",
        "铬金属": "Chrome",
        "果冻": "Jelly",
        "纸感": "Paper",
        "水晶": "Crystal",
        "日落": "Sunset",
        "极光": "Aurora",
        "柔光": "Soft Light",
        "冰川": "Ice",
        "墨影": "Ink",
        "琥珀": "Amber",
        "海洋": "Ocean",
        "云母": "Mica",
        "黑曜石": "Obsidian",
        "无边界": "Borderless",
        "天鹅绒": "Velvet",
        "霓虹": "Neon",
        "珍珠": "Pearl",
        "石墨": "Graphite",
        "玫瑰石英": "Rose Quartz",
        "碧湾": "Lagoon",
        "余烬": "Ember",
        "午夜": "Midnight",
        "香槟": "Champagne",
        "紫外光": "Ultraviolet",
        "显示更多（18 项）": "Show More (18)",
        "卡片顶部颜色强度": "Card Header Color Intensity",
        "窗口分组颜色强度": "Window Group Color Intensity",
        "顶部文字对比度": "Top Text Contrast",
        "预览：轻贴 · 搜索 · 分组": "Preview: ClipEase · Search · Groups",
        "系统默认": "System Default",
        "系统圆角": "System Rounded",
        "系统等宽": "System Monospaced",
        "字重": "Weight",
        "半粗": "Semibold",
        "中等": "Medium",
        "常规": "Regular",
        "已启用": "Enabled",
        "启动 macOS 后自动打开轻贴": "Open ClipEase when macOS starts",
        "用于打开或关闭底部历史窗口": "Used to open or close the history window",
        "修改": "Change",
        "恢复默认": "Restore Default",
        "正在记录新的复制内容": "Recording new copied content",
        "正在记录新的剪贴板内容": "Recording new clipboard content",
        "被忽略 App 中复制的内容不会进入历史": "Items copied in ignored apps are not saved to history",
        "暂未忽略任何 App。可点击添加，或在历史卡片右键菜单中添加。": "No apps are ignored. Add one here or from a history card's context menu.",
        "分组管理": "Group Management",
        "操作": "Actions",
        "目录与缓存": "Folders & Cache",
        "清理": "Cleanup",
        "性能采样": "Performance Sampling",
        "实时概览": "Live Overview",
        "最近日志": "Recent Logs",
        "当前运行 App": "Current App",
        "永久保存": "Keep Forever",
        "1 天": "1 Day",
        "3 天": "3 Days",
        "5 天": "5 Days",
        "7 天": "7 Days",
        "30 天": "30 Days",
        "永久": "Forever",
        "保留 1 天": "Keep 1 Day",
        "最多 1 MB": "Up to 1 MB",
        "内存": "Memory",
        "线程": "Threads",
        "主线程": "Main Thread",
        "已授权，可以自动粘贴到当前 App": "Authorized; auto-paste is available in the current app",
        "新建文本": "New Text",
        "编辑文本": "Edit Text",
        "编辑链接": "Edit Link",
        "编辑颜色": "Edit Color",
        "创建": "Create",
        "保存": "Save",
        "创建纯文本": "Create Plain Text",
        "保存纯文本": "Save Plain Text",
        "清除格式": "Clear Formatting",
        "内容不能为空": "Content cannot be empty",
        "保存失败": "Unable to save",
        "无法读取原富文本，不能保存": "Unable to read the original rich text; it cannot be saved.",
        "请输入 http:// 或 https:// 链接": "Enter an http:// or https:// link.",
        "请输入有效 HEX 颜色": "Enter a valid HEX color.",
        "此类型暂不支持编辑": "This item type cannot be edited.",
        "正在保存，请稍候": "Saving, please wait.",
        "保存更改？": "Save Changes?",
        "关闭前是否保存当前富文本内容？": "Save the current rich-text content before closing?",
        "不保存": "Don't Save",
        "需要在系统设置中批准": "Approval Required in System Settings",
        "未启用": "Not Enabled",
        "保存 1 天": "Keep for 1 Day",
        "保存 3 天": "Keep for 3 Days",
        "保存 5 天": "Keep for 5 Days",
        "保存 7 天": "Keep for 7 Days",
        "保存 30 天": "Keep for 30 Days",
        "当前构建暂不可用": "Unavailable in This Build",
        "未知状态": "Unknown Status",
        "暂停": "Pause",
        "恢复": "Resume",
        "暂无性能事件": "No performance events",
        "暂停到今日结束": "Pause Until End of Today",
        "请按下新的快捷键组合，Esc 取消": "Press a new shortcut combination; Esc to cancel",
        "已关闭自动检查，你仍然可以手动检查更新。": "Automatic checking is off; you can still check manually.",
        "每天静默检查一次 GitHub 最新正式 Release。": "Checks GitHub for the latest stable release once per day.",
        "加入交流群反馈问题，查看项目更新。": "Join the community to share feedback and follow project updates.",
        "感谢支持轻贴 ClipEase 的持续维护。": "Thank you for supporting ClipEase's ongoing development.",
        "导出备份包时包含图片和富文本附件": "Include images and rich-text attachments in backup exports",
        "清空图标缓存": "Clear Icon Cache",
        "清空图标缓存？": "Clear Icon Cache?",
        "此操作只会删除来源 App 图标缓存，不会删除历史记录。后续新复制内容会重新生成图标缓存。": "This only removes source-app icon cache files. It does not delete history. New copied items will recreate the icon cache.",
        "清空缩略图缓存？": "Clear Thumbnail Cache?",
        "此操作只会删除图片卡片使用的缩略图缓存，不会删除原始图片或历史记录。后续显示图片卡片时会重新生成。": "This only removes thumbnail cache files used by image cards. It does not delete original images or history. Thumbnails will be regenerated when image cards are shown.",
        "清理孤立附件？": "Clean Orphaned Attachments?",
        "此操作只会删除没有被当前历史记录引用的图片、缩略图和富文本文件，不会删除历史记录。": "This only removes images, thumbnails, and rich-text files that are not referenced by current history. It does not delete history records.",
        "此操作会删除所有普通和置顶记录，以及已保存的图片文件。": "This will delete all regular and pinned items, along with saved image files.",
        "清空缩略图缓存": "Clear Thumbnail Cache",
        "清理孤立附件": "Clean Orphaned Attachments",
        "只记录耗时、数量、阶段和类型，不记录剪贴板正文": "Records duration, count, stage, and type, never clipboard contents.",
        "暂无日志。操作历史窗口、搜索或预览后会出现在这里。": "No logs yet. Use the history window, search, or preview to create entries.",
        "暂无超过 16ms 的慢操作。": "No slow operations exceeding 16 ms.",
        "辅助功能权限已开启": "Accessibility Permission Enabled",
        "轻贴需要辅助功能权限": "ClipEase Needs Accessibility Permission",
        "现在可以使用快捷键打开历史窗口并自动粘贴。": "You can now use the shortcut and auto-paste.",
        "开启后才可以使用全局快捷键、自动粘贴和稳定的主窗口交互。": "Enable this to use global shortcuts, auto-paste, and reliable main-window interactions.",
        "卡片样式": "Card Style",
        "液态玻璃效果": "Liquid Glass Effect",
        "动态玻璃效果": "Animated Glass Effect",
        "窗口效果透明度": "Window Effect Opacity",
        "卡片效果透明度": "Card Effect Opacity",
        "恢复默认外观": "Restore Default Appearance",
        "文字样式": "Typography",
        "窗口与卡片文字分别设置": "Configure window and card text separately",
        "主题": "Theme",
        "字号": "Font Size",
        "窗口标题": "Window Title",
        "搜索框": "Search Field",
        "分组标签": "Group Labels",
        "工具栏按钮": "Toolbar Buttons",
        "卡片内容": "Card Content",
        "保存期限": "Retention Period",
        "置顶内容不会被自动清理": "Pinned items are never removed automatically",
        "开机自动启动": "Launch at Login",
        "记录状态": "Recording Status",
        "忽略 App": "Ignored Apps",
        "自动粘贴权限": "Auto-Paste Permission",
        "打开系统设置": "Open System Settings",
        "刷新状态": "Refresh Status",
        "添加 App": "Add App",
        "清空": "Clear",
        "关闭": "Close",
        "确认": "Confirm",
        "取消": "Cancel",
        "删除": "Delete",
        "重命名": "Rename",
        "颜色与图标": "Color & Icon",
        "搜索图标": "Search Icons",
        "分组名称": "Group Name",
        "新建分组": "New Group",
        "清空搜索": "Clear Search",
        "搜索筛选": "Search Filters",
        "更多操作": "More Actions",
        "加入分组": "Add to Group",
        "移动到分组...": "Move to Group…",
        "加入分组...": "Add to Group…",
        "移出分组": "Remove from Group",
        "取消置顶": "Unpin",
        "删除分组": "Delete Group",
        "删除分组和内容": "Delete Group and Items",
        "清空历史": "Clear History",
        "清空全部历史？": "Clear All History?",
        "删除分组？": "Delete Group?",
        "打开链接": "Open Link",
        "复制链接地址": "Copy Link Address",
        "复制为 Markdown 链接": "Copy as Markdown Link",
        "复制 HEX": "Copy HEX",
        "复制 RGB": "Copy RGB",
        "打开图片": "Open Image",
        "复制图像": "Copy Image",
        "复制图片路径": "Copy Image Path",
        "在 Finder 中显示": "Show in Finder",
        "打开文件": "Open File",
        "复制文件": "Copy File",
        "复制路径": "Copy Path",
        "已复制": "Copied",
        "已粘贴": "Pasted",
        "已删除": "Deleted",
        "已清空": "Cleared",
        "已保存": "Saved",
        "已新建分组": "New group created",
        "已重命名分组": "Group renamed",
        "分组名称不能为空": "Group name cannot be empty",
        "已有同名分组": "A group with that name already exists",
        "无法写入剪贴板": "Unable to write to the clipboard",
        "无法写入文件引用到剪贴板": "Unable to write file references to the clipboard",
        "无法写入文件路径到剪贴板": "Unable to write the file path to the clipboard",
        "未找到文件": "File not found",
        "未找到图片文件": "Image file not found",
        "图片文件无法读取": "Unable to read the image file",
        "无法写入图片到剪贴板": "Unable to write the image to the clipboard",
        "没有可复制的文本": "No text available to copy",
        "无法读取": "Unable to read",
        "数据正常": "Data is healthy",
        "没有可自动修复的问题": "No issues can be repaired automatically",
        "未知应用": "Unknown App",
        "新分组": "New Group",
        "已复制文本": "Text copied",
        "已复制富文本": "Rich text copied",
        "已复制链接": "Link copied",
        "已复制图片": "Image copied",
        "已复制颜色": "Color copied",
        "已复制文件引用": "File reference copied",
        "文件不可用，已复制文件路径": "File unavailable; file path copied",
        "无法加载图片预览": "Unable to load image preview",
        "正在读取文件内容...": "Reading file contents...",
        "无法读取文件内容": "Unable to read file contents",
        "[内容已截断]": "[Content truncated]",
        "文本": "Text",
        "文字": "Text",
        "链接": "Link",
        "图片": "Image",
        "颜色": "Color",
        "文件": "File",
        "文件夹": "Folder",
        "现在": "Now",
        "今天": "Today",
        "最近 7 天": "Last 7 Days",
        "最近 30 天": "Last 30 Days",
        "分享": "Share",
        "复制图片": "Copy Image",
        "识别文字": "Recognize Text",
        "无法加载链接预览": "Unable to load link preview",
        "不支持此链接预览": "This link preview is not supported",
        "正在加载链接预览": "Loading link preview",
        "文件路径不可用": "File path unavailable",
        "剪贴板记录没有可预览路径": "This clipboard item has no previewable path",
        "缺少路径": "Missing path",
        "路径缺失": "Path missing",
        "权限不足": "Insufficient permission",
        "占位文件": "Placeholder file",
        "状态未确认": "Status unverified",
        "路径未确认": "Path unverified",
        "未找到可拖出的文件": "No file available to drag",
        "已拖出可用文件": "Available files dragged",
        "文件引用": "File reference",
        "路径不可用": "Path unavailable",
        "缺失": "Missing",
        "无权限": "No permission",
        "占位": "Placeholder",
        "未确认": "Unverified",
        "已置顶": "Pinned",
        "来自 %@": "From %@",
        "忽略": "Ignore",
        "取消忽略": "Stop Ignoring",
        "复制来源 App 名称": "Copy Source App Name",
        "复制来源 Bundle ID": "Copy Source Bundle ID",
        "复制来源名称": "Source name copied",
        "无来源 Bundle ID": "No source Bundle ID",
        "已复制 Bundle ID": "Bundle ID copied",
        "恢复记录": "Resume Recording",
        "暂停记录": "Pause Recording",
        "移除": "Remove",
        "显示当前 App": "Show Current App",
        "复制 App 路径": "Copy App Path",
        "已授权": "Authorized",
        "需授权": "Authorization Required",
        "导出历史": "Export History",
        "导入历史": "Import History",
        "导出备份包": "Export Backup",
        "导入备份包": "Import Backup",
        "打开数据目录": "Open Data Folder",
        "打开图片目录": "Open Images Folder",
        "打开图标缓存": "Open Icon Cache",
        "打开缩略图缓存": "Open Thumbnail Cache",
        "刷新用量": "Refresh Usage",
        "压缩历史数据库": "Compact History Database",
        "检查数据": "Check Data",
        "删除所选": "Delete Selected",
        "暂无分组": "No Groups",
        "调整颜色和图标": "Adjust color and icon",
        "启用性能采样和日志记录": "Enable performance sampling and logging",
        "打开诊断目录": "Open Diagnostics Folder",
        "清理诊断日志": "Clear Diagnostic Logs",
        "慢操作": "Slow Operations",
        "最近错误": "Recent Errors",
        "暂无错误事件。": "No error events.",
        "暂无采样数据": "No sampling data",
        "打开 GitHub": "Open GitHub",
        "复制版本号": "Copy Version",
        "版本更新": "Version Updates",
        "自动检查": "Automatically Check",
        "检查中": "Checking",
        "检查更新": "Check for Updates",
        "支持与交流": "Support & Community",
        "加入交流群": "Join the Community",
        "赞赏支持": "Support the Project",
        "打开 Release": "Open Release",
        "下载 DMG": "Download DMG",
        "重新检查": "Check Again",
        "完成": "Done",
        "我已开启": "I've Enabled It",
        "快速开始": "Quick Start",
        "历史与卡片": "History & Cards",
        "搜索与分组": "Search & Groups",
        "预览与文件": "Preview & Files",
        "外观与字体": "Appearance & Typography",
        "记录与数据": "Recording & Data",
        "权限与常见问题": "Permissions & FAQ",
        "快捷键一览": "Keyboard Shortcuts",
        "从这里开始，快速找到你想做的事": "Start here to quickly find what you need.",
        "第一次使用": "First Use",
        "打开历史窗口": "Open the History Window",
        "复制即可记录": "Copy to Record",
        "选中并粘贴": "Select and Paste",
        "快速关闭": "Quick Close",
        "分组与置顶": "Groups & Pinning",
        "文件预览": "File Preview",
        "选择颜色主题": "Choose a Color Theme",
        "选择窗口效果": "Choose a Window Effect",
        "选择卡片样式": "Choose a Card Style",
        "调节透明度": "Adjust Opacity",
        "分别设置字体": "Set Fonts Separately",
        "导入、导出与备份": "Import, Export & Backup",
        "控制记录": "Control Recording",
        "辅助功能权限": "Accessibility Permission",
        "如何授权": "How to Authorize",
        "遇到问题先检查": "Troubleshoot First",
        "提示：⌘W 可关闭本帮助窗口": "Tip: ⌘W closes this Help window",
        "暂停 轻贴": "Pause ClipEase",
        "暂停 15 分钟": "Pause for 15 Minutes",
        "暂停 30 分钟": "Pause for 30 Minutes",
        "暂停 1 小时": "Pause for 1 Hour",
        "暂停 3 小时": "Pause for 3 Hours",
        "暂停 6 小时": "Pause for 6 Hours",
        "截止到今日": "Until End of Today",
        "已暂停记录": "Recording paused",
        "已恢复记录": "Recording resumed",
        "已暂停到今日结束": "Paused until the end of today",
        "已暂停 15 分钟": "Paused for 15 minutes",
        "已暂停 30 分钟": "Paused for 30 minutes",
        "已暂停 1 小时": "Paused for 1 hour",
        "已暂停 3 小时": "Paused for 3 hours",
        "已暂停 6 小时": "Paused for 6 hours",
        "已是最新版": "You're Up to Date",
        "发现数据问题": "Data Issues Found",
        "一键修复": "Repair Now",
        "修复数据问题？": "Repair Data Issues?",
        "轻贴会清理没有被当前历史引用的图片、缩略图和富文本附件，不会删除历史记录。": "ClipEase will remove images, thumbnails, and rich-text attachments that are no longer referenced by history. History records will not be deleted.",
        "已取消修复": "Repair cancelled",
        "修复完成": "Repair complete",
        "修复历史数据失败": "Failed to repair history data",
        "已打开诊断数据目录": "Diagnostics folder opened",
        "已按当前策略清理诊断日志": "Diagnostic logs cleaned using the current policy",
        "已打开系统设置": "System Settings opened",
        "已复制版本号": "Version copied",
        "只看置顶": "Showing pinned items only",
        "显示置顶内容": "Show pinned items",
        "一个简单流程": "A Simple Flow",
        "为什么需要权限": "Why Permission Is Needed",
        "主窗口已取消钉住": "Main window unpinned",
        "主窗口已钉住": "Main window pinned",
        "仍需授权": "Authorization still required",
        "从预览继续操作": "Continue from Preview",
        "关闭独立预览": "Close Detached Preview",
        "关闭附着预览；独立预览也支持 ⌘W。": "Close the attached preview. Detached previews also support ⌘W.",
        "关闭预览": "Close Preview",
        "再次粘贴": "Paste Again",
        "分组不存在": "Group not found",
        "分组内容已变化，请重新确认": "Group contents changed. Please confirm again.",
        "切换卡片": "Switch Cards",
        "创建和管理分组": "Create and manage groups",
        "删除不需要的内容": "Delete unneeded items",
        "删除所选分组？": "Delete Selected Groups?",
        "删除选中卡片。": "Delete the selected card.",
        "历史数据库无需压缩": "History database does not need compaction",
        "历史窗口": "History Window",
        "发现重复历史": "Duplicate History Found",
        "取消导入": "Cancel Import",
        "取消钉住主窗口": "Unpin Main Window",
        "可预览": "Previewable",
        "右键菜单": "Context Menu",
        "回车没有自动粘贴": "Enter did not auto-paste",
        "图片与文字": "Images & Text",
        "字体与可读性": "Typography & Readability",
        "导入": "Import",
        "导入与导出": "Import & Export",
        "导入历史失败": "Failed to import history",
        "导入轻贴历史": "Import ClipEase History",
        "导入轻贴备份包": "Import ClipEase Backup",
        "导出": "Export",
        "导出历史失败": "Failed to export history",
        "导出轻贴历史": "Export ClipEase History",
        "导出轻贴备份包": "Export ClipEase Backup",
        "已保存并复制新链接": "Saved and copied the new link",
        "已删除分组": "Group deleted",
        "已刷新存储用量": "Storage usage refreshed",
        "已加入分组": "Added to group",
        "已取消修改快捷键": "Shortcut edit cancelled",
        "已取消导入备份包": "Backup import cancelled",
        "已取消置顶": "Unpinned",
        "已在 Finder 中显示": "Shown in Finder",
        "已复制 App 路径": "App path copied",
        "已复制 HEX": "HEX copied",
        "已复制 Markdown 链接": "Markdown link copied",
        "已复制 RGB": "RGB copied",
        "已复制图像": "Image copied",
        "已复制图片路径": "Image path copied",
        "已复制文件": "File copied",
        "已复制文件路径": "File path copied",
        "已复制来源名称": "Source name copied",
        "已复制纯文本": "Plain text copied",
        "已复制链接地址": "Link address copied",
        "已导出历史": "History exported",
        "已导出备份包": "Backup exported",
        "已恢复默认快捷键": "Default shortcut restored",
        "已打开 DMG 下载": "DMG download opened",
        "已打开 GitHub": "GitHub opened",
        "已打开 Release": "Release opened",
        "已打开交流群": "Community opened",
        "已打开图片": "Image opened",
        "已打开文件": "File opened",
        "已打开目录": "Folder opened",
        "已打开链接": "Link opened",
        "已授权自动粘贴": "Auto-paste authorized",
        "已显示当前 App": "Current app shown",
        "已显示性能测试入口": "Performance test tools shown",
        "已更新分组图标": "Group icon updated",
        "已更新分组排序": "Group order updated",
        "已更新快捷键": "Shortcut updated",
        "已清空历史": "History cleared",
        "已清空图标缓存": "Icon cache cleared",
        "已清空忽略 App": "Ignored apps cleared",
        "已清空缩略图缓存": "Thumbnail cache cleared",
        "已移出分组": "Removed from group",
        "已移除忽略 App": "Ignored app removed",
        "已选择": "Selected",
        "常用卡片操作": "Common Card Actions",
        "应用与窗口": "App & Windows",
        "开启辅助功能权限": "Enable Accessibility Permission",
        "开机启动与全局快捷键": "Launch at Login & Global Shortcut",
        "当前构建暂不支持开机自启动": "Launch at login is not supported by this build",
        "当前筛选结果数量 / 全部数量": "Filtered results / all items",
        "当前系统会以兼容玻璃呈现": "Your system will use compatible glass rendering",
        "录制中...": "Recording...",
        "快捷键需要包含 Command、Control 或 Option": "Shortcut must include Command, Control, or Option",
        "快速选中": "Quick Select",
        "忽略特定 App": "Ignore Specific Apps",
        "性能测试数据": "Performance Test Data",
        "打开预览": "Open Preview",
        "找不到旧内容": "Can't Find Older Items",
        "把内容加入分组": "Add Items to Groups",
        "把预览变成普通窗口": "Turn Preview into a Regular Window",
        "拖出预览": "Detach Preview",
        "收起": "Collapse",
        "无法打开 GitHub": "Unable to open GitHub",
        "无法打开 Release": "Unable to open Release",
        "无法打开交流群": "Unable to open the community",
        "无法打开目录": "Unable to open folder",
        "无法打开链接": "Unable to open link",
        "无法识别所选 App": "Unable to identify the selected app",
        "无法识别来源 App": "Unable to identify source app",
        "无法转换 RGB": "Unable to convert to RGB",
        "显示全部历史": "Show All History",
        "暂无来源": "No source",
        "未选择": "Not selected",
        "检查分组内容失败": "Failed to check group contents",
        "检查历史数据失败": "Failed to check history data",
        "正在修复数据...": "Repairing data...",
        "正在准备完整历史...": "Preparing complete history...",
        "先完成这几步，就可以把复制过的内容随时找回来。": "Complete these steps first, then you can find copied content whenever you need it.",
        "选中、复制、粘贴、置顶和删除，都围绕一张历史卡片完成。": "Select, copy, paste, pin, and delete all happen from a history card.",
        "用搜索缩小范围，再用分组整理常用内容。": "Narrow results with search, then organize frequent items with groups.",
        "先查看再操作；需要时把预览拖成独立窗口。": "Preview before acting; detach it into its own window when needed.",
        "按你的习惯调整颜色、玻璃效果、卡片和字体。": "Adjust colors, glass effects, cards, and typography to suit your workflow.",
        "掌握暂停记录、保存期限和历史数据管理。": "Manage recording pauses, retention, and history data.",
        "了解自动粘贴的权限要求，以及遇到问题时先检查什么。": "Learn auto-paste permission requirements and what to check when something goes wrong.",
        "键盘操作可以让查找和粘贴更快。": "Keyboard shortcuts make finding and pasting faster.",
        "轻贴会在后台记录新的复制内容": "ClipEase records newly copied content in the background",
        "先选中，再决定如何使用": "Select an item, then choose what to do with it",
        "搜索不会改变你的原始历史": "Search never changes your original history",
        "预览可以安全地先看后用": "Preview safely before using an item",
        "外观设置会立即应用到窗口": "Appearance changes apply to windows immediately",
        "暂停记录不会删除已有历史": "Pausing recording does not delete existing history",
        "没有辅助功能权限也能正常复制": "Copying works normally without Accessibility permission",
        "快捷键会随当前焦点自动让位给输入框": "Shortcuts yield automatically when a text field has focus",
        "复制一次，之后就能在轻贴里搜索、预览和再次粘贴。": "Copy once, then search, preview, and paste it again in ClipEase.",
        "单击卡片或用方向键移动选择，再复制、粘贴、置顶或打开更多操作。": "Click a card or use arrow keys to select it, then copy, paste, pin, or open more actions.",
        "先输入关键词；需要长期整理时，再把内容放进分组或置顶。": "Start with a keyword; for long-term organization, add items to groups or pin them.",
        "按空格查看内容，拖动预览顶部区域可把它变成可移动的普通窗口。": "Press Space to preview; drag the preview header to make it a movable regular window.",
        "主题、窗口效果、卡片样式、透明度和字体均可独立调整。": "Theme, window effects, card style, opacity, and typography can all be adjusted independently.",
        "清空、导入、导出和备份会影响你的历史数据；执行前请留意确认提示。": "Clearing, importing, exporting, and backing up affect history data; review confirmation prompts before continuing.",
        "只有“自动粘贴到其他 App”需要授权；其他历史浏览和复制功能不受影响。": "Only auto-pasting into other apps requires permission; browsing and copying history are unaffected.",
        "当搜索框或可编辑文本正在输入时，轻贴会优先保留正常的文字编辑行为。": "When entering text in search or an editor, ClipEase preserves normal text editing behavior.",
        "点击菜单栏中的轻贴图标。历史窗口会显示最近记录的内容。": "Click the ClipEase menu bar icon. The history window shows recently recorded items.",
        "轻贴会记录复制的文字、链接、图片、文件和富文本。": "ClipEase records copied text, links, images, files, and rich text.",
        "单击一张卡片后按回车，即可将内容粘贴到先前正在使用的 App。": "Select a card and press Return to paste it into the app you were using previously.",
        "按 Esc 或点击历史窗口外部即可收起窗口。": "Press Esc or click outside the history window to dismiss it.",
        "1. 复制": "1. Copy",
        "在任意 App 中复制内容。": "Copy content in any app.",
        "2. 查找": "2. Find",
        "打开轻贴，通过卡片或搜索定位需要的内容。": "Open ClipEase and find what you need through cards or search.",
        "3. 使用": "3. Use",
        "回车粘贴，或先预览、复制、置顶和分组。": "Press Return to paste, or preview, copy, pin, and group first.",
        "移动选择": "Move Selection",
        "单击卡片，或使用左右方向键在可见卡片间切换。": "Click a card or use Left and Right Arrow to move among visible cards.",
        "将选中内容粘贴回之前使用的 App；未授予辅助功能权限时会只复制到剪贴板。": "Paste the selected item into the previously used app; without Accessibility permission it is copied to the clipboard instead.",
        "复制与纯文本": "Copy & Plain Text",
        "复制原内容，或在需要去除格式时复制、粘贴为纯文本。": "Copy original content, or copy and paste as plain text when formatting should be removed.",
        "置顶常用内容": "Pin Frequent Items",
        "置顶后的内容会排在前面，也不会因保存期限自动清理。": "Pinned items stay at the front and are not removed automatically by retention.",
        "选中卡片后按 Delete，或从右键菜单中删除。": "Press Delete on a selected card, or remove it from the context menu.",
        "可按内容类型执行打开、在 Finder 中显示、复制路径、复制 Markdown、加入分组等操作。": "Depending on the item type, open it, reveal it in Finder, copy its path or Markdown, add it to a group, and more.",
        "在更多菜单中选择“新建文本”，可以手动保存一条备忘内容。": "Choose New Text from the More menu to save a note manually.",
        "按 ⌘1 到 ⌘9 可直接选中当前可见区域内对应位置的卡片。": "Press ⌘1 through ⌘9 to select the corresponding visible card.",
        "直接输入关键词": "Type a Keyword",
        "搜索会查找文本、链接标题、文件名、文件路径和来源 App。": "Search looks through text, link titles, file names, file paths, and source apps.",
        "缩小内容范围": "Narrow the Scope",
        "配合当前分组和来源 App 筛选，更容易找到以前复制过的内容。": "Filter by the current group and source app to find older copied content more easily.",
        "清空搜索继续浏览": "Clear Search and Keep Browsing",
        "清除关键词后，会回到当前范围内的完整历史。": "Clear keywords to return to the complete history in the current scope.",
        "可为常用内容建立分组，并调整分组名称、图标和颜色。": "Create groups for frequent items and adjust their names, icons, and colors.",
        "从卡片右键菜单选择分组；之后可从分组栏快速切换。": "Choose a group from a card's context menu, then switch quickly from the group bar.",
        "置顶不是分组": "Pinning Is Not Grouping",
        "置顶用于让单条内容始终靠前；分组用于长期分类整理。": "Pinning keeps an individual item at the front; groups organize items by category over time.",
        "查看选中内容": "View Selected Item",
        "选中卡片后按空格，可预览文字、图片、链接和文件。": "Press Space on a selected card to preview text, images, links, and files.",
        "可识别图片中的文字；富文本、文本和 PDF 会尽量保留可阅读、可选择的内容。": "Text can be recognized in images; rich text, text, and PDFs preserve readable, selectable content when possible.",
        "支持的文件会显示内容；无法预览时仍会保留文件名、路径和打开方式。": "Supported files show their contents; when preview is unavailable, the file name, path, and open action remain available.",
        "窗口和卡片外观": "Window & Card Appearance",
        "可设为浅色、深色或跟随系统；设置窗口和主窗口会同步更新。": "Choose Light, Dark, or Follow System; settings and main windows update together.",
        "可在液态玻璃、普通及更多视觉效果之间切换；默认会折叠较多选项。": "Switch between Liquid Glass, Standard, and more visual effects; extra options are collapsed by default.",
        "卡片提供与窗口效果相同的丰富样式，可单独调整。": "Cards offer the same rich styles as window effects and can be adjusted independently.",
        "窗口和卡片的效果透明度可独立调整；部分顶部区域也有单独的强度控制。": "Window and card effect opacity can be adjusted independently; some top regions have their own intensity controls.",
        "可调整窗口标题、搜索、分组、工具栏按钮和卡片内容的字体、大小及字重。": "Adjust the font, size, and weight for window titles, search, groups, toolbar buttons, and card content.",
        "玻璃效果开关": "Glass Effect Toggle",
        "需要更强的视觉效果时可开启液态玻璃；也可关闭以获得更朴素的界面。": "Enable Liquid Glass for a stronger visual effect, or disable it for a simpler interface.",
        "在外观设置中可恢复默认配置。": "Restore default configuration in Appearance settings.",
        "暂停或恢复": "Pause or Resume",
        "暂停后，新的复制内容不会写入历史；已有记录不会受到影响。": "While paused, newly copied content is not saved to history; existing records are unaffected.",
        "可在设置中将 App 加入忽略列表，避免来自该 App 的复制内容被记录。": "Add an app to the ignored list in Settings to avoid recording content copied from it.",
        "可在设置中控制登录时启动和全局快捷键。": "Control launch at login and the global shortcut in Settings.",
        "普通历史会按设置的期限自动清理；置顶内容不会自动清理。": "Regular history is cleared according to retention settings; pinned items are never cleared automatically.",
        "可在设置中导出历史、导入历史或创建/恢复备份包。": "Export and import history, or create and restore backup packages in Settings.",
        "清理数据": "Clean Up Data",
        "可清空历史，也可清理图标、缩略图缓存或检查孤立附件。执行前会要求确认。": "Clear history, clean icon and thumbnail caches, or check orphaned attachments. Confirmation is requested before each action.",
        "自动将选中内容粘贴到其他 App 时，macOS 需要辅助功能权限。": "macOS requires Accessibility permission to paste selected content automatically into other apps.",
        "没有权限时": "Without Permission",
        "轻贴仍能记录、搜索、预览和复制内容；回车操作会改为只复制到剪贴板。": "ClipEase can still record, search, preview, and copy; pressing Return copies to the clipboard instead.",
        "打开设置中的权限页面，按提示前往系统设置完成授权。": "Open the Permissions page in Settings, then follow the instructions to authorize in System Settings.",
        "确认记录未暂停，并检查来源 App 是否被加入忽略列表。": "Confirm recording is not paused and the source app is not on the ignored list.",
        "没有新记录": "No New Records",
        "确认已授予辅助功能权限，并确保目标 App 仍可接收文本输入。": "Confirm Accessibility permission is granted and the target app can still receive text input.",
        "尝试清除搜索条件、切换分组，或检查保存期限和手动清理操作。": "Try clearing search filters, switching groups, or checking retention and manual cleanup actions.",
        "预览当前选中的卡片。": "Preview the currently selected card.",
        "将选中内容粘贴到之前使用的 App。": "Paste the selected item into the previously used app.",
        "在需要去除格式时使用。": "Use this when formatting should be removed.",
        "复制选中内容，或仅复制其纯文本形式。": "Copy the selected item, or only its plain-text form.",
        "复制 / 复制纯文本": "Copy / Copy Plain Text",
        "置顶或取消置顶选中卡片。": "Pin or unpin the selected card.",
        "在可见卡片之间移动选择。": "Move selection among visible cards.",
        "选择第 1 到第 9 张可见卡片。": "Select visible card 1 through 9.",
        "打开轻贴设置。": "Open ClipEase Settings.",
        "编辑当前可编辑内容。": "Edit the current editable item.",
        "快速切换记录状态。": "Quickly toggle recording status.",
        "独立预览可使用 Esc 或 ⌘W 关闭，不会关闭历史主窗口。": "A detached preview can be closed with Esc or ⌘W without closing the history window.",
        "预览中仍可复制、打开、显示到 Finder 或关闭窗口。": "From preview you can still copy, open, reveal in Finder, or close the window.",
        "拖动预览顶部区域，即可将它变成可移动、可调整大小的独立窗口。": "Drag the top of a preview to turn it into a movable, resizable detached window.",
        "正在检查更新": "Checking for Updates",
        "正在连接 GitHub 获取最新正式 Release。": "Connecting to GitHub for the latest stable release.",
        "发现新版本": "New Version Available",
        "检查失败，稍后重试": "Update Check Failed",
        "可能是网络或 GitHub 暂时不可用。你可以稍后重新检查，也可以打开 GitHub 自行下载。": "The network or GitHub may be temporarily unavailable. Try again later or download directly from GitHub.",
        "开机自启动已开启，登录 macOS 后会自动打开轻贴": "Launch at login is enabled. ClipEase will open after you sign in to macOS.",
        "开机自启动已关闭，登录 macOS 后不会自动打开轻贴": "Launch at login is disabled. ClipEase will not open after you sign in to macOS.",
        "开机自启动需要在系统设置中批准": "Launch at login needs approval in System Settings.",
        "开机自启动未能开启": "Unable to enable launch at login.",
        "开机自启动暂不支持": "Launch at login is unavailable in this build.",
        "粗体": "Bold",
        "液态玻璃需要 macOS 26 或更高版本": "Liquid Glass requires macOS 26 or later.",
        "轻贴已暂停记录": "ClipEase recording is paused",
        "分组颜色": "Group Color",
        "轻贴 ClipEase\n简洁好用的 macOS 粘贴板历史助手\n版本 %@": "ClipEase\nA simple and useful macOS clipboard history manager\nVersion %@"
    ]
}

func L(_ source: String) -> String {
    AppLocalization.text(source)
}
